import type { Metadata } from 'next'

const SITE_NAME = 'Feeradar'
const SITE_URL = 'https://feeradar.xyz'
const DEFAULT_DESCRIPTION = 'Generated by create next app'
const DEFAULT_OG_IMAGE = '/og-image.png'
const DEFAULT_LOCALE = 'en_EN'

interface BuildMetadataParams {
  title?: string
  description?: string
  path?: string
  image?: string
}

export function buildMetadata({ title, description = DEFAULT_DESCRIPTION, path = '', image = DEFAULT_OG_IMAGE }: BuildMetadataParams = {}): Metadata {
  const fullTitle = title ? `${title} | ${SITE_NAME}` : SITE_NAME
  const url = `${SITE_URL}${path}`

  return {
    title: fullTitle,
    description,
    metadataBase: new URL(SITE_URL),
    alternates: {
      canonical: url
    },
    openGraph: {
      title: fullTitle,
      description,
      url,
      siteName: SITE_NAME,
      images: [{ url: image, width: 1200, height: 630 }],
      locale: DEFAULT_LOCALE,
      type: 'website'
    },
    twitter: {
      card: 'summary_large_image',
      title: fullTitle,
      description,
      images: [image]
    }
  }
}
