allowBuilds:
  '@prisma/engines': true
  argon2: true
  core-js-pure: true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
minimumReleaseAgeExclude:
  - '@hookform/resolvers@5.9.0'
